version: '3'

services:
    courses_database:
        image: postgres:alpine
        ports:
         - "5432:5432"
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: Toor@1234
          POSTGRES_DB: courses_db
        volumes:
         - courses-data:/var/lib/postgresql/data

    adminer:
        image: adminer
        ports:
         - 8080:8080

volumes:
    courses-data: